export {default as member1 } from "./member-1.jpeg";
export {default as member2 } from "./member-2.jpeg";
export {default as member3 } from "./member-3.jpeg";
export {default as member4 } from "./member-4.jpeg";
export {default as profile2} from "./profile-2.jpeg";
export {default as profile3} from "./profile-3.jpeg";
export {default as profile4} from "./profile-4.jpeg";
export {default as profile5} from "./profile-5.jpg";
export {default as profile6} from "./profile-6.png";
export {default as hero_image} from "./hero-image.png";
export {default as about_image} from "./about-image.jpeg";
export {default as building_1} from "./building-1.jpeg";
export {default as building_2} from "./building-2.jpeg";
export {default as building_3} from "./building-3.jpeg";
export {default as building_4} from "./building-4.jpeg";
export {default as building_5} from "./building-5.jpeg";
export {default as building_6} from "./building-6.jpeg";
export {default as building_7} from "./building-7.jpeg";
export {default as building_8} from "./building-8.jpeg";
export {default as building_9} from "./building-9.jpeg";
export {default as building_10} from "./building-10.jpeg";
export {default as blog_1} from "./blog-1.jpeg";
export {default as blog_2} from "./blog-2.jpeg";
export {default as blog_3} from "./blog-3.jpeg";